### ISSUE TITLE
Compiled Dll

### ISSUE THREAD

**Issue by TsunamiWind** [orcfoss/RbxHooks#5]
[RbxHooks.txt](https://github.com/orcfoss/RbxHooks/files/7277052/RbxHooks.txt)

Rename to RbxHooks.dll

**Comment by ittehgeps** [comment]
Please do not trust this, Epiculy (OP) has a terrible rep in the orc and shouldn't be trusted. Compile the DLL yourself.

**Comment by p0s0** [comment]
yeah, epiculy (OP) also made rhodum (if you were in the ORC in 2021, you know, if not, it was a revival that was largely considered amongst the community as a RAT)
